version: 2
updates:
  - allow:
      - dependency-type: all
    directory: /
    package-ecosystem: composer
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Europe/Berlin
    versioning-strategy: increase
    reviewers:
      - "imdhemy"
