name: 📝 Task
description: Create a task issue.

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the task
    validations:
      required: true
